name: 'BoringCache Node.js'
description: 'Cache once. Reuse everywhere. Setup Node.js via mise and cache Node.js + node_modules with BoringCache.'
author: 'BoringCache'

branding:
  icon: 'package'
  color: 'green'

inputs:
  cli-version:
    description: 'BoringCache CLI version (e.g., v1.0.0). Set to "skip" to disable automatic CLI setup.'
    required: false
    default: 'v1.6.0'
  workspace:
    description: 'BoringCache workspace (e.g., "my-workspace" or "org/workspace")'
    required: false
  cache-tag:
    description: 'Cache tag prefix for BoringCache. Defaults to repository name. Used as prefix for node/modules caches.'
    required: false
    default: ''
  node-version:
    description: 'Node.js version to install. Auto-detected from .node-version, .nvmrc, or .tool-versions if not specified.'
    required: false
  working-directory:
    description: 'Working directory for the project'
    required: false
    default: '.'
  cache-node:
    description: 'Cache the Node.js installation'
    required: false
    default: 'true'
  cache-modules:
    description: 'Cache node_modules directory'
    required: false
    default: 'true'
  verbose:
    description: 'Enable verbose CLI output for debugging'
    required: false
    default: 'false'
  exclude:
    description: 'Glob pattern to exclude files from cache digest (e.g., "*.out")'
    required: false
  turbo-remote-cache:
    description: 'Enable Turborepo remote cache via a local BoringCache proxy. Replaces local .turbo/cache directory caching with per-object CAS dedup.'
    required: false
    default: 'false'
  turbo-api-url:
    description: 'External Turbo remote cache API URL. When set, skips starting a local proxy and uses this URL directly.'
    required: false
  turbo-token:
    description: 'Turbo remote cache token. Auto-generated for local proxy mode; required when turbo-api-url is set.'
    required: false
  turbo-team:
    description: 'Turbo team name (sets TURBO_TEAM env var)'
    required: false
  turbo-port:
    description: 'Port for the local Turbo remote cache proxy'
    required: false
    default: '4227'
  cache-build:
    description: 'Auto-detect and cache build system outputs (Turborepo, Nx, Next.js, Yarn Berry, pnpm store)'
    required: false
    default: 'true'
  build-cache-paths:
    description: 'Manual build cache paths in name:path format (newline-separated). Overrides auto-detected paths by name.'
    required: false
    default: ''
  save-always:
    description: 'Save cache even if the job fails'
    required: false
    default: 'false'

outputs:
  node-version:
    description: 'Installed Node.js version'
  cache-hit:
    description: 'Whether the modules cache was restored'
  node-cache-hit:
    description: 'Whether the Node.js cache was restored'
  cache-tag:
    description: 'Cache tag prefix used'
  node-tag:
    description: 'Cache tag used for Node.js'
  modules-tag:
    description: 'Cache tag used for node_modules'
  workspace:
    description: 'Resolved workspace name'

runs:
  using: 'node24'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: "success() || inputs.save-always == 'true'"
